name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Logseq Publish
        id: publish
        uses: pengx17/logseq-publish@0.1.7
        with:
          dest: www
          # Temporary until master gets heading block urls
          version: nightly@sha256:89e32c07eee2fac2506ddbdee4d3fbcd35d2c1ea1020fccc6b7464f4f146c35f
      - name: Add .nojekyll file
        run: touch www/.nojekyll
      - name: Deploy to GitHub Pages
        id: deploy-github-pages
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
        with:
          branch: html-pages
          folder: www
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll
